import '@/lib/orpc.server' //prerendering for ssr
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/lib/theme-provider";
import {AuthProvider} from "@/components/ui/AuthProvider";
import {Providers} from "@/lib/providers";
import {Toaster} from "@/components/ui/sonner";


// Rest of the code

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body


            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <AuthProvider>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <Providers>{children}</Providers>
                <Toaster closeButton position="top-center"/>
            </ThemeProvider>
        </AuthProvider>

        </body>
        </html>
    );
}
